#!/bin/sh

### BEGIN INIT INFO
# Provides:          light-controller
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=lightwaverf
PIDFILE=/var/run/$NAME.pid

#This is the command to be run, give the full pathname
DAEMON=/opt/tornado-light-controller/run.py
DAEMON_OPTS=

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting daemon: " $NAME
        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --no-close --exec $DAEMON -- $DAEMON_OPTS 1> /var/log/$NAME.log 2> /var/log/$NAME.err
        log_end_msg 0
        ;;
  stop)
        log_daemon_msg  "Stopping daemon: "$NAME
        start-stop-daemon --stop --quiet  --retry 30 --pidfile $PIDFILE
        log_end_msg 0
        ;;
  restart)
        log_daemon_msg "Restarting daemon: "$NAME
        start-stop-daemon --stop --quiet  --retry 30 --pidfile $PIDFILE
        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        log_end_msg 0
        ;;

  *)
        echo "Usage: "$1" {start|stop|restart}"
        exit 1
esac

exit 0
